# 네트워크 구성 설정
pc1_ai:
  ip: "192.168.0.10" # AI 서버 실제 IP
  port: 5000         # TCP 분석 요청용

pc2_main:
  ip: "192.168.0.20" # 메인 서버 실제 IP
  tcp_port: 8000     # 제어용
  udp_port_front: 6000 # 전방 카메라 영상 수신용
  udp_port_cart: 6001  # 카트 카메라 영상 수신용

pc3_ui:
  ip: "192.168.0.30" # 쇼핑카트 대시보드 IP
  port: 7000         # 알람 및 상품정보 수신용 (TCP)